# Generated by Django 6.1 on 2026-08-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customer_company_name_customer_keycloak_synced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('RETAIL', 'Cliente Minorista'), ('CORPORATE', 'Cliente Corporativo'), ('VIP', 'Cliente VIP')], max_length=50, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000000.0, max_digits=15)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=5000000000.0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('REVIEWED', 'En Revisión'), ('RESOLVED', 'Resuelto / Aprobado')], default='PENDING', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_alerts', to='authentication.customer')),
            ],
        ),
    ]
