# Generated by Django 6.1 on 2026-08-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_transactionlimit_kycalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CI_FRONT', 'Cédula de Identidad (Anverso)'), ('CI_BACK', 'Cédula de Identidad (Reverso)'), ('RUC_CERT', 'Certificado de RUC'), ('INCOME_PROOF', 'Comprobante de Ingresos'), ('KYC_FORM', 'Formulario KYC Completado')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Verificación'), ('VERIFIED', 'Verificado y Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.customer')),
            ],
        ),
    ]
