from django.urls import path
from .views import (
    KeycloakSSOLoginView,
    DashboardView,
    PermissionListView,
    RoleListCreateView,
    RoleDetailView,
    RolePermissionAssignView,
    RoleAdminTemplateView,
    CustomerListCreateView,
    CustomerDetailView,
    CustomerAdminTemplateView,
    CorporateCustomerRegisterView,
    CustomerClassificationView,
    CorporateCustomerAdminTemplateView,
    TransactionLimitView,
    KYCAlertView,
    TransactionLimitValidationView,
    UserMenuView
)

urlpatterns = [
    path('auth/login/', KeycloakSSOLoginView.as_view(), name='keycloak-sso-login'),
    path('dashboard/', DashboardView.as_view(), name='user-dashboard'),
    path('permissions/', PermissionListView.as_view(), name='permission-list'),
    path('roles/', RoleListCreateView.as_view(), name='role-list-create'),
    path('roles/<int:pk>/', RoleDetailView.as_view(), name='role-detail'),
    path('roles/<int:pk>/permissions/', RolePermissionAssignView.as_view(), name='role-permission-assign'),
    path('roles/admin/', RoleAdminTemplateView.as_view(), name='roles-admin-ui'),
    path('customers/', CustomerListCreateView.as_view(), name='customer-list-create'),
    path('customers/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customers/admin/', CustomerAdminTemplateView.as_view(), name='customers-admin-ui'),
    path('corporate-customers/register/', CorporateCustomerRegisterView.as_view(), name='corporate-customer-register'),
    path('customers/classification/', CustomerClassificationView.as_view(), name='customer-classification'),
    path('customers/corporate/admin/', CorporateCustomerAdminTemplateView.as_view(), name='corporate-customer-admin-ui'),
    path('limits/', TransactionLimitView.as_view(), name='transaction-limits'),
    path('kyc-alerts/', KYCAlertView.as_view(), name='kyc-alerts'),
    path('kyc-alerts/<int:pk>/', KYCAlertView.as_view(), name='kyc-alert-detail'),
    path('transactions/validate-limit/', TransactionLimitValidationView.as_view(), name='transaction-validate-limit'),
    path('menu/', UserMenuView.as_view(), name='user-menu-api'),
]
